# Generated by Django 2.2 on 2019-07-02 19:12

from django.db import migrations, models
import django.db.models.deletion
import nabard.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=50, verbose_name='عنوان طرح')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('app_file', models.FileField(upload_to='apps/%Y/%m', validators=[nabard.validators.validate_archived_file], verbose_name='فایل اپلیکیشن')),
                ('powerpoint_file', models.FileField(upload_to='powerpoints/%Y/%m', validators=[nabard.validators.validate_powerpoint_file], verbose_name='فایل ارائه')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nabard.Team', verbose_name='تیم')),
            ],
        ),
    ]
