# Generated by Django 2.2.2 on 2019-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='app_file',
            field=models.FileField(upload_to='media/apps/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='team',
            name='powerpoint_file',
            field=models.FileField(upload_to='media/powerpoints/%Y/%m'),
        ),
    ]
